version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: rate-limiter-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  rate-limiter:
    build: .
    container_name: rate-limiter-app
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - RATE_LIMIT_IP_REQUESTS_PER_SECOND=5
      - RATE_LIMIT_IP_BLOCK_DURATION_MINUTES=5
      - TOKEN_LIMIT_abc123=10:5
      - TOKEN_LIMIT_def456=20:10
      - TOKEN_LIMIT_ghi789=50:15
      - SERVER_PORT=8080
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

volumes:
  redis_data:
