steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/cep-temperature', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cep-temperature']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'cep-temperature', '--image', 'gcr.io/$PROJECT_ID/cep-temperature', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
